// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bszcwxrjhvbvixrdnzvf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzemN3eHJqaHZidml4cmRuenZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjI4OTYsImV4cCI6MjA2NTQ5ODg5Nn0.MrRUmjHT1KWa5nPo4GP4ZHsVAI5yd8a0yxLGYayZ0og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);